bounswe/bounswe2018group5

KarpuzTwitterApp/README.md
KarpuzTwitterApp/handlers/main.py
KarpuzTwitterApp/requirements.txt
KarpuzTwitterApp/templates/index.html
KarpuzTwitterApp/templates/main.html

- Add jinja2 to requirements.
- Add pip install command to README.md
- Separate the main.html and index.html

Adds missing parts and changing HTML structure.

---

KarpuzTwitterApp/templates/index.html
KarpuzTwitterApp/templates/locationtweets.html

- Opens the show media option in the tweet
- Add functionality to map drag and change frame of the map.

Include some improvements

---

.gitignore
KarpuzTwitterApp/end_points.py
KarpuzTwitterApp/handlers/commonfollowers.py
KarpuzTwitterApp/logic.py
KarpuzTwitterApp/templates/commonfollowers.html
KarpuzTwitterApp/templates/index.html
KarpuzTwitterApp/templates/main.html

Obviously took a lot of inspiration from common-followings feature (also lots of code) (:
If that pr is merged first, we need to delete the one same function used `get_user_details`
Also @emingure you need to fix a couple of things otherwise the code doesn't work

Integrate Common Followers feature

---

KarpuzTwitterApp/end_points.py
KarpuzTwitterApp/handlers/searchusers.py
KarpuzTwitterApp/logic.py
KarpuzTwitterApp/templates/index.html
KarpuzTwitterApp/templates/main.html
KarpuzTwitterApp/templates/searchusers.html

I added the tweepy package to requirements txt please before try, install tweepy.

Search users

---

KarpuzTwitterApp/handlers/locationtweets.py
KarpuzTwitterApp/logic.py
KarpuzTwitterApp/templates/locationtweets.html

Move controls from handler to logic function.

---

.gitignore
KarpuzTwitterApp/logic.py
KarpuzTwitterApp/requirements.txt
KarpuzTwitterApp/tests/test_logic.py

I added a test case for location query function.

Add pytest for location function.

---

frontend/package.json
frontend/src/views/LandingPage/LandingPage.jsx

- Add Helmet Package and Edit Landing Page Title #139

Helmet Package

---

.gitignore
backend/api/settings.py
backend/api/urls.py
backend/project/models.py
backend/project/urls.py
backend/project/views.py
backend/requirements.txt
backend/user/authentication.py
backend/user/models.py
backend/user/urls.py
backend/user/views.py

authentication functionalities

---

frontend/src/components/CustomInput/CustomInput.jsx
frontend/src/components/Form/LoginForm.jsx
frontend/src/components/Form/RegisterForm.jsx
frontend/src/redux/auth/Actions.js
frontend/src/redux/auth/Reducer.js
frontend/src/redux/sagas/api.js
frontend/src/redux/sagas/saga.js
frontend/src/services/HttpService.js
frontend/src/services/cookies.js
frontend/src/views/LoginPage/LoginPage.jsx
frontend/src/views/RegisterPage/RegisterPage.jsx

Add functionality to register and login button.

---

backend/api/urls.py
backend/project/models.py
backend/project/urls.py
backend/project/views.py
backend/user/authentication.py
backend/user/models.py
backend/user/views.py

Major project endpoints implemented

---

frontend/src/components/Card/ProjectCard.jsx
frontend/src/views/HomePage/HomePage.jsx

Now get all projects from backend and show all of them in the home page.

Show projects in the home page.

---

android/app/src/main/java/com/karpuz/karpuz/Activity/LoginActivity.kt
android/app/src/main/java/com/karpuz/karpuz/Activity/SignupActivity.kt
android/app/src/main/java/com/karpuz/karpuz/Extensions/CharSequence+isValidEmail.kt
android/app/src/main/java/com/karpuz/karpuz/Extensions/Context+Toast.kt
android/app/src/main/java/com/karpuz/karpuz/Extensions/EditText+Error.kt
android/app/src/main/res/layout/activity_welcome.xml

…text to welcome screen, add extensions, add folders Helper and Extensions

#142 Add email/password Validation

---

backend/user/views.py

Merge develop/backend to master. 
Not required build.

Register endpoint returns token

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/karpuz/karpuz/Activity/HomeActivity.kt
android/app/src/main/java/com/karpuz/karpuz/Network/Config.kt
android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPI.kt
android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPIModels.kt
android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPIProvider.kt
android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPIService.kt
android/app/src/main/java/com/karpuz/karpuz/Network/MockKarpuzAPIProvider.kt
android/app/src/main/res/layout/activity_home.xml

@enisimsar I'm not totally sure I'm on the right track. Can you give some tips?

#150 implement network & network mock

---

frontend/src/components/Card/ProjectCard.jsx
frontend/src/redux/user/Reducer.js
frontend/src/views/UserProfile/UserProfile.jsx

- Fix update profile alert bug and selection bug
- Hide tags in the project cards

Fix bugs about update profile

---

backend/api/settings.py
backend/requirements.txt

Add sentry.io Integration to Django

---

backend/api/settings.py
backend/project/models.py
backend/project/urls.py
backend/project/views.py
backend/user/views.py

Project model modified, used ReferenceField for user ids. Search index created and search endpoint implemented.
Before deploying:
db.projects.getIndexes();
db.projects.dropIndex('<index_name>')
Note: <index_name> wil be returned as the result of the first command in the second element of the list

Project model modified. Search index created and search endpoint implemented.

---

backend/project/urls.py
backend/project/views.py

Changes to methods that deal with freelancer and owner id.

Get own projects endpoint implemented. 

---

backend/project/models.py
backend/project/urls.py
backend/project/views.py

Bid model and endpoints w/ minor changes

---

frontend/src/components/Form/LoginForm.jsx
frontend/src/components/Sidebar/Sidebar.jsx
frontend/src/redux/auth/Reducer.js
frontend/src/routes/PrivateRoute.jsx

Login Logout bug fixed.

---

frontend/src/components/Badge/Badge.jsx
frontend/src/components/Card/ProjectCard.jsx
frontend/src/components/DateTimePicker/DateTimePicker.jsx
frontend/src/components/DropDown/ProjectDropdown.jsx
frontend/src/components/Modal/AddProjectModal.jsx
frontend/src/services/combineStyles.js
frontend/src/views/HomePage/HomePage.jsx
frontend/src/views/ProjectsPage/ProjectsPage.jsx

API connections will be added later
closes #232

Add project edit, discard and delete components.

---

backend/project/views.py
backend/user/views.py

Add id to user json

---

backend/project/views.py

Accept bid changes

---

backend/api/utils.py
backend/project/views.py
backend/user/models.py
backend/user/urls.py
backend/user/views.py

Rating model and endpoints

---

backend/api/utils.py
backend/project/models.py
backend/project/urls.py
backend/project/views.py
backend/user/urls.py
backend/user/views.py

Major changes to url patterns.

Closes #250

---

frontend/src/redux/sagas/api.js
frontend/src/services/HttpService.js

Fix all used endpoints.

---

backend/api/utils.py
backend/user/models.py
backend/user/urls.py
backend/user/views.py

/api/user/portfolio/?id=
/api/user/portfolio/
Body: 
- title
- description
- date (optional)
- project_id (optional)
/api/user/portfolio/
Body: 
- portfolio_id
- title (optional)
- description (optional)
- date (optional)
- project_id (optional)
/api/user/portfolio/?id=

Portfolio model and endpoints

---

backend/api/utils.py
backend/project/models.py
backend/project/urls.py
backend/project/views.py

`body={"project_id": "string"}`
```
body={"project_id": "string",  _// in PUT method_
"milestones": {"milestone1_name": "object",
"milestone2_name": "object"} 
}
```

Project enhancements

---

frontend/src/components/DateTimePicker/DateTimePicker.jsx
frontend/src/components/DropDown/PortfolioDropdown.jsx
frontend/src/components/DropDown/ProjectDropdown.jsx
frontend/src/views/UserProfile/OtherUserProfile.jsx

Edit portfolio was missing in the previous pull request.

Edit portfolio is added

---

backend/api/utils.py
backend/project/views.py
backend/user/models.py
backend/user/urls.py
backend/user/views.py

- Wallet model and endpoints added.
- Finish project modified to automatically make the transaction upon project completion.

Wallet model and endpoints

---

backend/api/utils.py
backend/project/models.py
backend/project/urls.py
backend/project/views.py

`  body = {"milestone_id"(required), "status", "name", "detail", "deadline"}`
closes #280, #293

Add milestone model and endpoints

---

backend/api/attachment.py
backend/api/utils.py

Now delete method takes file name in request body instead of get parameter

changed delete method

---

frontend/src/components/Form/RegisterForm.jsx
frontend/src/redux/auth/Reducer.js
frontend/src/views/ProjectPage/ProjectPage.jsx

I added simple validation for register.

Register validation with api response.

---

frontend/src/components/Card/PortfolioCard.jsx
frontend/src/views/UserProfile/UserProfile.jsx

add Portfolio Attachments

---

backend/api/semantic_tags.py
backend/api/urls.py
backend/api/utils.py
backend/project/models.py
backend/requirements.txt
backend/user/models.py

#262 
**GET:**
```/api/tag/```
body:
```
{
"keys": [
"key1",   //for example Django
"key2"   //for example Backend
]
}
```
response:
```
{
"response": true,
"search": {
"key1": [
{
"description": "desc1",
"label": "label1",
"wikidata_id": "id1"
},
{
"description": "desc2",
"label": "label2",
"wikidata_id": "id2"
}
],
"key2": [
{
"description": "desc1",
"label": "label1",
"wikidata_id": "id1"
},
{
"description": "desc2",
"label": "label2",
"wikidata_id": "id2"
}
]
}
}
```
**POST:**
```/api/tag/?id=<project_id or portfolio_id>&wikidata_id=<wikidata_id of a tag>```
adds tag to object which has the given id.
**DELETE:**
```/api/tag/?id=<project_id or portfolio_id>&wikidata_id=<wikidata_id of a tag>```
deletes tag from object which has the given id.

semantic tag features are added-#262

---

frontend/src/components/DropDown/ProjectDropdown.jsx
frontend/src/redux/project/Actions.js
frontend/src/redux/sagas/api.js
frontend/src/redux/sagas/saga.js

Add new editable fields

---

backend/user/views.py

#319 - Prevent multiple ratings for a project

---

backend/api/utils.py
backend/project/views.py
backend/user/views.py

Add publicity to project get endpoint

---

backend/api/recommendation_engine.py
backend/api/semantic_tags.py
backend/api/settings.py
backend/api/urls.py
backend/project/models.py
backend/requirements.txt

#347 
**GET:**
```/api/recommend/?id=<user_id or project_id>```
**NOTE:** If id is not provided, then requester's id is considered
response:
```
{
"response": true,
"recommendation": [
{
---recommended project or user1----         
},
{
---recommended project or user2----
}
]
}
If id is a project id, then users are recommended and vice versa.

Recommendation backend

---

backend/api/recommendation_engine.py
backend/api/semantic_tags.py
backend/api/utils.py
backend/user/models.py
backend/user/urls.py
backend/user/views.py

#352 
**GET:**
```/api/user/message/```
response:
```
{
"response": true,
"conversations": [
{
"messages": [
{
"body": "emin_to_admin",
"sender": {
"id": "5c2a9abde0414a000c682481",
"type": null,
"username": "eminayar",
"ratings": {
"rated": []
},
"bio": null,
"avg_rating": 0,
"full_name": "Emin Ayar",
"profile_image": null
},
"receiver": {
"id": "5c02cd748eee9a000a59d63f",
"type": null,
"username": "adminreyiz",
"ratings": {
"rated": []
},
"bio": null,
"avg_rating": 0,
"full_name": "admin reyiz",
"profile_image": "5c02cd748eee9a000a59d63f1543703647.jpg"
}
},
{
----message2----
},
{
----message3----
}
],
"user1": {
"id": "5c2a9abde0414a000c682481",
"type": null,
"username": "eminayar",
"ratings": {
"rated": []
},
"bio": null,
"avg_rating": 0,
"full_name": "Emin Ayar",
"profile_image": …
```

messaging endpoints are implemented- #352

---

frontend/src/components/DateTimePicker/DateTimePicker.jsx
frontend/src/components/Header/Header.jsx
frontend/src/components/Modal/AddPortfolioModal.jsx
frontend/src/components/Modal/AddProjectModal.jsx

Bug in portfolio addition

---

backend/api/recommendation_engine.py
backend/api/semantic_tags.py

keep some data in memory to fast access

recommendation engine optimization

---

backend/user/views.py

create tag should have taken user as tagged instead of portfolio
